apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactjs-app
  template:
    metadata:
      labels:
        app: reactjs-app
    spec:
      containers:
      - name: project-demo
        image: varunh1718/myfirstcicd-dev-may:1.0
        ports:
        - containerPort: 80
