# EKS cluster service file, for accessing

apiVersion: v1
kind: Service
metadata:
  name: react-app  # Matches your deployment name
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: react-app  # Matches the label in your deployment
  type: LoadBalancer  # Exposes the service externally
